FROM python:3.9-slim
WORKDIR /app

# Cruciaal: kopieer de lijst en installeer de tools
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Kopieer de rest van de code (waaronder merger_app.py)
COPY . .

CMD ["python", "merger_app.py"]